#!/bin/sh
echo "Checking for previous installations..."

if [ -d /usr/lib/enigma2/python/Plugins/Extensions/SevenHD/user ]; then
    cp -r /usr/lib/enigma2/python/Plugins/Extensions/SevenHD/user/* /tmp
fi

if [ -f /usr/lib/enigma2/python/Plugins/Extensions/SevenHD/data/skin-user.xml ]; then
    cp /usr/lib/enigma2/python/Plugins/Extensions/SevenHD/data/skin-user.xml /tmp
fi

if [ -f /usr/lib/enigma2/python/Plugins/Extensions/SevenHD/plugin.py ]; then
    rm -rf /usr/lib/enigma2/python/Plugins/Extensions/SevenHD
    rm -rf /usr/lib/enigma2/python/Components/Converter/SevenHD*
    rm -rf /usr/lib/enigma2/python/Components/Renderer/SevenHD*
    echo "                                                           "
    echo "           SevenHD configuration plugin                    "
    echo "              was found and removed!                       "
    echo "                                                           "
fi

echo "                                                           "
echo "         The Skin SevenHD is now being installed...        "
echo "                                                           "
exit 0
