#!/bin/sh
echo "                                                           "
echo "        The Skin SevenHD is now being removed...           "
echo "                                                           "
